from __future__ import annotations

import os
from decimal import Decimal
from .models import InvoiceInput, CalculationResult


def format_money(x: Decimal) -> str:
    return f"£{x:,.2f}"


def render_frontsheet_html(inv: InvoiceInput, res: CalculationResult) -> str:
    method_label = "On Gross" if inv.method == "gross" else "Sequential"
    retention_pct = f"{(inv.retention_rate * 100):.2f}%"
    discount_pct = f"{(inv.discount_rate * 100):.2f}%"

    invoice_pdf_name = os.path.basename(inv.invoice_pdf) if inv.invoice_pdf else ""

    return f"""
<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>Subcalc Front Sheet - {inv.invoice_number}</title>
  <style>
    body {{ font-family: Arial, Helvetica, sans-serif; margin: 24px; color: #111; }}
    h1 {{ font-size: 20px; margin: 0 0 8px; }}
    h2 {{ font-size: 16px; margin: 16px 0 8px; color: #333; }}
    .meta, .calc {{ border-collapse: collapse; width: 100%; max-width: 720px; }}
    .meta td {{ padding: 6px 8px; border-bottom: 1px solid #eee; }}
    .calc th, .calc td {{ text-align: left; padding: 8px; border-bottom: 1px solid #e6e6e6; }}
    .right {{ text-align: right; }}
    .muted {{ color: #666; }}
    .totals {{ font-weight: bold; }}
    .badge {{ display: inline-block; background: #eef; color: #225; padding: 2px 6px; border-radius: 4px; font-size: 12px; }}
    .footer {{ margin-top: 24px; font-size: 12px; color: #666; }}
    .small {{ font-size: 12px; }}
  </style>
  <meta name=\"generator\" content=\"subcalc\" />
  <meta name=\"calc-method\" content=\"{inv.method}\" />
  <meta name=\"retention\" content=\"{inv.retention_rate}\" />
  <meta name=\"discount\" content=\"{inv.discount_rate}\" />
  <meta name=\"net\" content=\"{res.net}\" />
  <meta name=\"retention-amount\" content=\"{res.retention}\" />
  <meta name=\"discount-amount\" content=\"{res.discount}\" />
  <meta name=\"subtotal-after-retention\" content=\"{res.subtotal_after_retention}\" />
  <meta name=\"gross\" content=\"{inv.gross}\" />
  <meta name=\"supplier\" content=\"{inv.supplier}\" />
  <meta name=\"invoice-number\" content=\"{inv.invoice_number}\" />
  <meta name=\"invoice-date\" content=\"{inv.invoice_date}\" />
  <meta name=\"invoice-pdf\" content=\"{invoice_pdf_name}\" />
  <meta name=\"description\" content=\"{inv.description}\" />
  <meta name=\"csv-lines\" content=\"{inv.csv_lines}\" />
  <meta name=\"supplier\" content=\"{inv.supplier}\" />
  <meta name=\"x-frontend-printable\" content=\"true\" />
  <meta name=\"x-note\" content=\"Attach this sheet to the paper invoice\" />
</head>
<body>
  <h1>Subcontractor Payment Calculation <span class=\"badge\">{method_label}</span></h1>
  <table class=\"meta\">
    <tr><td><strong>Supplier</strong></td><td>{inv.supplier}</td></tr>
    <tr><td><strong>Invoice No.</strong></td><td>{inv.invoice_number}</td></tr>
    <tr><td><strong>Invoice Date</strong></td><td>{inv.invoice_date}</td></tr>
    <tr><td><strong>Description</strong></td><td>{inv.description}</td></tr>
    <tr><td><span class=\"muted\">Original PDF</span></td><td class=\"muted\">{invoice_pdf_name or '—'}</td></tr>
  </table>

  <h2>Calculation</h2>
  <table class=\"calc\">
    <tr><th>Item</th><th class=\"right\">Rate</th><th class=\"right\">Amount</th></tr>
    <tr><td>Gross</td><td class=\"right\">—</td><td class=\"right\">{format_money(inv.gross)}</td></tr>
    <tr><td>Retention</td><td class=\"right\">{retention_pct}</td><td class=\"right\">− {format_money(res.retention)}</td></tr>
    <tr><td>Subtotal after retention</td><td class=\"right\">—</td><td class=\"right\">{format_money(res.subtotal_after_retention)}</td></tr>
    <tr><td>Discount</td><td class=\"right\">{discount_pct}</td><td class=\"right\">− {format_money(res.discount)}</td></tr>
    <tr class=\"totals\"><td>Net Payable</td><td class=\"right\">—</td><td class=\"right\">{format_money(res.net)}</td></tr>
  </table>

  <div class=\"footer\">
    <div>Generated by subcalc. Method: {method_label}. Rates: Retention {retention_pct}, Discount {discount_pct}.</div>
    <div class=\"small\">Print this page and attach to the paper invoice.</div>
  </div>
</body>
</html>
"""


def save_frontsheet(inv: InvoiceInput, res: CalculationResult, out_dir: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    fname = f"frontsheet_{inv.invoice_number}.html"
    fpath = os.path.join(out_dir, fname)
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(render_frontsheet_html(inv, res))
    return fpath

